### PR TITLE
Rename homebrew formula subdirctory

### PR DESCRIPTION
**Pull request by sharkAndshark**
Rename hombrew formula directory from `homebrew-formula` to `HomebrewFormula` based on the [homebrew doc](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap#creating-a-tap).

### CODE REVIEW

**Comment by sharkAndshark** [comment]
I made a test on my M1 Mac.  I could install martin on it after this change.

**Comment by sharkAndshark** [comment]
I made a test on my M1 Mac. I could install martin on it after this change.
Before this change:

```shell
brew tap maplibre/martin https://github.com/maplibre/martin.git
brew install maplibre/martin/martin
Warning: No available formula or cask with the name "maplibre/martin/martin".
```
After this change:

```shell
brew tap maplibre/martin https://github.com/maplibre/martin.git
brew install maplibre/martin/martin
==> Fetching dependencies for maplibre/martin/martin: openssl@3
==> Fetching openssl@3
==> Downloading https://ghcr.io/v2/homebrew/core/openssl/3/manifests/3.1.3
######################################################################### 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/openssl/3/blobs/sha256:297a2c1c
######################################################################### 100.0%
==> Fetching maplibre/martin/martin
...
==> Summary
🍺  /opt/homebrew/Cellar/martin/0.8.7: 3 files, 13.2MB, built in 3 seconds
==> Running `brew cleanup martin`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Caveats
==> martin
Martin requires a database connection string.
It can be passed as a command-line argument or as a DATABASE_URL environment variable.
  martin postgres://postgres@localhost/db
```

**Comment by sharkAndshark** [comment]
Hi @nyurik   Have a good day :)
Any idea about automatically update the version number in formula in `ci`. How about  shell command to retrieve version info from `cargo.toml`?

**Review by nyurik — APPROVED** [review]
Thanks, looks good!  I keep thinking if it would make sense to create a separate repository just for this, and automate its update with a github action... But that would be a separate PR

**Pull request merged**
