### PR TITLE
Update document file names for outside links

### PR DESCRIPTION
**Pull request by sharkAndshark**
- [x] Remove chapter numbers
- [x] Update file name of `using-endpoints.md` back
- [x] Update links

### CODE REVIEW

**Comment by nyurik** [comment]
.md is required - try running it with `just book` and you will see empty pages

**Comment by sharkAndshark** [comment]
> .md is required - try running it with `just book` and you will see empty pages



> .md is required - try running it with `just book` and you will see empty pages

Fixed.

**Comment by nyurik** [comment]
i made a pr against your branch - please review and merge

**Review by nyurik — APPROVED** [review]
thanks!!

**Comment by sharkAndshark** [comment]
> i made a pr against your branch - please review and merge

Merged. : )

**Comment by sharkAndshark** [comment]
Defintely we need link checks in ci.  It's easy to miss links... @nyurik

**Pull request merged**
