### PR TITLE
Update some deps (the most important is actix-web to 3.x)

### PR DESCRIPTION
**Pull request by mdtrooper**
...and some changes in the code run with new versions.

:beers:

### CODE REVIEW

**Comment by mdtrooper** [comment]
Give me some days to fix it.

**Comment by mdtrooper** [comment]
I don't know how grow the % "codecov/patch". Could you help me?

**Review by stepankuzmin — APPROVED** [review]
LGTM

**Comment by stepankuzmin** [comment]
Hi @mdtrooper 

Thanks a lot for this

**Pull request merged**
