### PR TITLE
Allow ignore  small geometries 

### PR DESCRIPTION
**Pull request by sharkAndshark**
Implements #756

### CODE REVIEW

**Comment by nyurik** [comment]
just to clarify - do you plan to make this PR remove polygons that are too small for a given zoom level, or do you want to deal with merging "polygon dust" as discussed in #756? Please update the PR description. Thx!

**Comment by sharkAndshark** [comment]
Hi @nyurik  :)  
I'm still thinking of these things and it would be better to build the talk based on code and test so I make this draft PR. Sorry for this late description.
The basic idea is something like impose a  random number to make the cluster of small buildings still can be seen on screen.

```SQL
...
WHERE 
ST_TRANSFORM("geom",3857) && ST_TileEnvelope(3, 1, 1) 
AND  ( ST_AREA ( ST_TRANSFORM ( geom, 3857 ) ) >= ( ( 40075016.68 / ( 2 ^ z * 512 ) ) ^ 2 ) )   
AND RANDOM() > 0.3  
-- the random threshold should be from config maybe
...
```
Yes,It's for #756   
let's talk and test more on this PR :)

**Review by nyurik — COMMENTED** [review]
looking at the current SQL changes - I looked at [ST_AsMVTGeom](https://postgis.net/docs/ST_AsMVTGeom.html) -- and it has this text:

> From 3.0, Wagyu can be chosen at configure time to clip and validate MVT polygons. This library is faster and produces more correct results than the GEOS default, but it might drop small polygons.

Which means that exactly the same filtering is already being done by SQL?

Note that this is different from merging tiny chunks

**Comment by sharkAndshark** [comment]
I think you are right @nyurik   
The [code in st_asmvtgeom related to this PR](https://github.com/postgis/postgis/blob/af3e63085419434590f2d52963ca89105e52492f/postgis/lwgeom_out_mvt.c#L42) is here:
```c
/* If possible, peek into the bounding box before deserializing it to discard small geometries
	 * We don't check COLLECTIONTYPE since that might be a collection of points */
	if (type == LINETYPE || type == POLYGONTYPE || type == MULTILINETYPE || type == MULTIPOLYGONTYPE)
	{
		GBOX gserialized_box;
		/* We only apply the optimization if the bounding box is available */
		if (gserialized_fast_gbox_p(geom_in, &gserialized_box) == LW_SUCCESS)
		{
			/* Shortcut to drop geometries smaller than the resolution */
			double geom_width = gserialized_box.xmax - gserialized_box.xmin;
			double geom_height = gserialized_box.ymax - gserialized_box.ymin;

			/* We use half of the square height and width as limit: We use this
			 * and not area so it works properly with lines */
			double bounds_width = ((bounds->xmax - bounds->xmin) / extent) / 2.0;
			double bounds_height = ((bounds->ymax - bounds->ymin) / extent) / 2.0;
			if (geom_width < bounds_width && geom_height < bounds_height)
			{
				PG_RETURN_NULL();
			}
		}
	}
```

**Comment by CommanderStorm** [comment]
> ST_AsMVTGeom [...] might drop small polygons

Given that this PR only adresses geometires too small for a given zoom level and this is already handled in ST_AsMVTGeom, I think we need to "go back to the drawing board" on this one.

=> lets re-group in https://github.com/maplibre/martin/issues/756 on the exact configuration options/feature we should support (we can always reopen this PR if it comes to that ^^)

**Pull request closed without merging**
