### PR TITLE
Added a test for schema.table.column containing special chars

### PR DESCRIPTION
**Pull request by nyurik**
This just adds a test for the unusual case of a table with quotes, spaces, and dots in their identifiers.  Another similar test should be added for functions.

### CODE REVIEW

**Comment by nyurik** [comment]
@sharkAndshark hi, any concerns with this PR?

**Comment by sharkAndshark** [comment]
I'd love to add a test for function but really busy these days, I will add it hours later

**Comment by sharkAndshark** [comment]
Or maybe merge it first, add function test next PR?

**Review by sharkAndshark — APPROVED** [review]

**Comment by nyurik** [comment]
Yeah, lets do another PR for that, thx!

**Pull request merged**
