### PR TITLE
Add a homebrew CI test

### PR DESCRIPTION
**Pull request by nyurik**
Trying to automate homebrew testing, so that eventually we can be certain our mac users are ok.

HELP NEEDED: I (@nyurik) don't have a Mac.

So far I already see that it is loading a lot of un-needed (?) homebrew stuff when adding a tap - so perhaps we need to move it to another repo all-together, like `maplibre/martin-homebrew` ?

This PR temporarily deletes all other CIs to avoid wasting resources -- they will be re-added later.

See #618 #674

### CODE REVIEW

**Comment by sharkAndshark** [comment]
I have a Mac but I know nothing about `homebrew` packaging..  Is there any thing I could help before reading a lot of documents about `homebrew`?

**Comment by nyurik** [comment]
Sorry, I know even less about homebrew :)

**Comment by sharkAndshark** [comment]
I'm reading docs then ..😂

**Comment by nyurik** [comment]
So it seems the installation passes now (thanks @sharkAndshark !), so now the questions are:
* do we want to move homebrew formular to a new repo, e.g. `maplibre/martin-homebrew`
* are there any additional tests we can do?
* is there a way to automate formula update on each release

**Comment by sharkAndshark** [comment]
@nyurik 
* I'm happy to move it to a standalone repo as `homebrew` clone whole martin repo when tapping. It can save user's disk space 
* Maybe run an integration test against a PostGIS?  But we need to duplicate some test shell if we are in an new repo:  `maplibre/martin-homebrew`.. 
* Need more research on. A simple idea is use shell to parse `cargo.toml`?

**Comment by nyurik** [comment]
So this is now a fairly low priority, but if you do notice how other repos structure homebrew, it would help. Seems weird if each installation env (homebrew, snap, nix, ...) would need its own repo tbh, but maybe there is a common pattern other repos follow?

**Comment by sharkAndshark** [comment]
How about we stay a single repo until we figure out the best practice?

**Comment by nyurik** [comment]
sure, we can do that too.  I do want to have some CI that tests & updates the code as part of the release process. Esp maybe have a regularly running (cron job) workflow that validates that homebrew still works.

**Comment by nyurik** [comment]
already done in the homebrew-martin repo

**Pull request closed without merging**
