### PR TITLE
Switch default encoding to gzip for now

### PR DESCRIPTION
**Pull request by nyurik**
GZip is significantly faster, so for now lets use that until brotli project gains some performance, and until we get proper after-compression caching.

### CODE REVIEW

**Comment by sharkAndshark** [comment]
https://github.com/maplibre/martin/blob/7107db5887f6233f3066077513978cbfe2757c46/martin/src/srv/tiles.rs#L200-L204

Seems this should be updated

**Comment by sharkAndshark** [comment]
https://github.com/maplibre/martin/blob/7107db5887f6233f3066077513978cbfe2757c46/martin/src/srv/tiles.rs#L281-L297

And maybe more tests should be added or updated here.

**Comment by nyurik** [comment]
Thx @sharkAndshark!  Turns out it was never properly working -- it was always using the list of accepted encoding and ignored the order of the supported encodings... So we may have to rework that code.  I re-worked the tests and removed the confusing default, but this is currently broken. Will try to get back to it soonish

**Comment by sharkAndshark** [comment]
Hi @nyurik  I make a [PR](https://github.com/nyurik/martin/pull/6) to this, Could you give it a review?

**Review by sharkAndshark — APPROVED** [review]

**Pull request merged**
