### PR TITLE
Make x-rewrite-url an opt-in feature

### PR DESCRIPTION
**Pull request by nyurik**
This PR is based on #551

Per #503 make `X-Rewrite-URL` an opt-in feature due to a potential for security issues (unconfirmed).  This will allow only the users who needed it to opt-in into it, either via cli or a config flag.

### CODE REVIEW

**Comment by maxammann** [comment]
I'm basically 100% sure there is no security risk. At least there is no indication that there is one.

**Comment by nyurik** [comment]
@maxammann do you think we should continue to support this out of the box despite all frameworks removing this functionality, or should we let the users opt-in for it, thus hugely reducing the uncertainty?  If i was researching Martin, and saw this function built in, I would do a quick search, and see that it has caused some security issues - and would be less likely to jump on it. But if i have the control of enabling it, each shop can evaluate if this is concerning to them or not.

**Comment by maxammann** [comment]
I see a few options:
1. Remove the feature completely and add add an alternative to statically define a URL prefix in the `config.yml`
2. Partially remove the feature and only support the `Forwarded` header (Using custom paths will no longer be possible)
3. Keep the feature as is and use the HTTP header name `X-Rewrite-Url`
4. Keep the feature as is and use some other HTTP header name for communicating between the proxy and martin

All options are equally secure in our thread model. I think martin just arbitrarily went with the `X-Rewrite-Url` header. There is no relation to the vulnerabilities found online.
I found [here](https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/05-Authorization_Testing/02-Testing_for_Bypassing_Authorization_Schema#testing-for-special-request-header-handling) a hint on how that header is used sometimes.

I fail to see a connection between how we use the header and the reported vulnerabilities.

**Comment by nyurik** [comment]
@maxammann I am not proposing to remove the Forwarded feature at all (host & protocol forwarding) - that one is totally fine and should stay as is.  I am only concerned with the `X-Rewrite-Url` having some yet-not-understood security concern, and so let the users enable it only when they specifically need it.  I don't think we should enable it for everyone though.

**Comment by maxammann** [comment]
I see it this way: Either it is a security issue or it isn't according to our thread model. If it isn't then we should not introduce some arbitrary config flag for it because we are unsure about security implications. If it is a security issue -> drop it.

Though I can see potential for an other similar config flag: `behind_proxy`.

If we are not behind a proxy (the default case) then we can disable some parts of request handling. E.g. we can also ignore the Forwarded header.

**Comment by nyurik** [comment]
won't merge, thx for feedback

**Pull request closed without merging**
