### PR TITLE
adjust book style

### PR DESCRIPTION
**Pull request by sharkAndshark**
- [ ] allow fold/unfold chapter lists.I tried [this](https://rust-lang.github.io/mdBook/format/configuration/renderers.html#outputhtmlfold) but it didn't work.
- [x] add edit links to the originating docs.
- [x] add link to martin repository. Should it link to [marin](https://github.com/maplibre/martin) or [matin doc](https://github.com/maplibre/martin/tree/main/docs)?
- [ ] other stuffs need to talk?

[comprehensive-rust](https://github.com/google/comprehensive-rust)  has something like this(see [mdbook doc](https://rust-lang.github.io/mdBook/format/configuration/renderers.html#html-renderer-options)),does marin want it?

```toml
[output.html]
curly-quotes = true
```
Some stuffs [comprehensive-rust](https://github.com/google/comprehensive-rust) used but I think martin dosen't need.
* [mdbook-svgbob](https://github.com/boozook/mdbook-svgbob)
* [mdbook-exerciser](https://github.com/google/comprehensive-rust/tree/main/mdbook-exerciser)

### CODE REVIEW

**Comment by nyurik** [comment]
looks good so far!  Do you think we can somehow cleanup the sidebar too?  At the moment it is repetetive - it duplicates the title and the topic on every line:

| Martin | Mdbook guide |
|---|---|
| image | image |

**Comment by nyurik** [comment]
I figured we might as well iteratively merge these things, no point in a "one big change"

**Comment by sharkAndshark** [comment]
I need a little bit research on the sidebar

**Comment by sharkAndshark** [comment]
@nyurik  The nested sidebar is about the summary.md.  After adjusting the summary.md,it nested
image

using_with_clients.md:
```markdown
# Using with clients
This section details the using martin with various clients:

* maplibre
* leaflet
* deck.gl
* mapbox

```
Summary.md:
```markdown
[Introduction](introduction.md)

- [Requirements](requirements.md)

- [Installation](installation.md)

- [Usage](usage.md)

- [API](API.md)

- [Using with clients](using_with_clients.md)
    - [Using with MapLibre](using-with-MapLibre.md)

    - [Using with Leaflet](using-with-Leaflet.md)

    - [Using with deck.gl](using-with-deck.gl.md)

    - [Using with Mapbox](using-with-Mapbox.md)

- [Source List](source-list.md)

- [Table Sources](table-sources.md)

- [Composite Sources](composite-sources.md)

- [Function Sources](function-Sources.md)

- [MBTile and PMTile Sources](MBTile-and-PMTile-Sources.md)

- [Command-line Interface](command-line-Interface.md)

- [Environment Variables](environment-Variables.md)

- [Configuration File](configuration-File.md)

- [PostgreSQL Connection String](PostgreSQL-Connection-String.md)

- [Using with Docker](using-with-Docker.md)

- [Using with Docker Compose](using-with-Docker-Compose.md)

- [Using with Nginx](using-with-Nginx.md)

- [Building from Source](building-from-Source.md)

- [Debugging](debugging.md)

- [Development](development.md)

- [Recipes](recipes.md)

```

**Comment by nyurik** [comment]
Thx @sharkAndshark, I guess we should cleanup that summary, e.g. put all `Using with docker/...` under one group, like "How to run" or "Platform"', or some other heading like that. My concern that currently it looks kinda ugly with each topic repeated twice on the sidebar - https://maplibre.org/martin/

**Pull request merged**
