### PR TITLE
Add cargo binstall support

### LINKED ISSUE #1005: Standardize release filenames and add `cargo binstall` support
`cargo binstall` support is very easy to add, but will require us to modify the naming convention for the build artifacts.  Should be a simple fix.  See [binstall docs](https://github.com/cargo-bins/cargo-binstall/blob/main/SUPPORT.md) on the release name pattern.  They also have defaults, so in theory it may be possible to just rename the release files without adding `[package.metadata.binstall]`.

* [ ] rename release files to be accessible by binstall's magic fields
* [ ] add `[package.metadata.binstall]` to Martin `Cargo.toml` if needed
* [ ] add `[package.metadata.binstall]` to mbtiles `Cargo.toml` if needed

I am not certain if binstall will handle multiple binaries inside one archive, or if we will need to separate `mbtiles` and `martin` binaries into multiple archive?

### PR DESCRIPTION
**Pull request by sharkAndshark**
Try to fix #1005
- [x] Add cargo binstall support
- [x] Update links
- [x] Update [home-brew](https://github.com/maplibre/homebrew-martin) by another [PR](https://github.com/maplibre/homebrew-martin/pull/8)
- [x] To check is there anything to do for `mbtiles`

### CODE REVIEW

**Comment by nyurik** [comment]
This is exactly what i was looking for, thank you!!!  Let me know when ready to merge. Although one thing:  we will need to merge this right before the release, or else we will have incorrect documentation links for a while, and that wouldn't be good.

**Comment by sharkAndshark** [comment]
**As there is no convenient way to verify this PR works, I explain it here.**

To install packages, `binstall` will download package from `pkg-url` and find `bin-dir` in it .

* pkg-url specifies the package download URL for a given target/version, templated
* pkg-fmt overrides the package format for download/extraction (defaults to: tgz)
* bin is the name of a specific binary, inferred from the crate configuration
* bin-dir specifies the binary path within the package, templated (with an .exe suffix on windows)
* binary-ext is the string .exe if the target is for Windows, or the empty string otherwise


## The default pkg-url template in this PR
The default pkg-url template in this PR is `{ repo }/releases/download/v{ version }/{ name }-{ target }{ archive-suffix }`  

For `archive-suffix`, `tgz`, eg the `.tar.gz`, is the default. As `binstall` will try various archive suffix one by one, so i didn't add `[package.metadata.binstall.overrides.x86_64-pc-windows-msvc]` for overriding windows.

```shell
cargo binstall martin --version 0.10.0 -v
...
DEBUG Checking for package at: 'https://github.com/maplibre/martin/releases/download/0.10.0/martin-x86_64-unknown-linux-gnu-v0.10.0.tar'
...
DEBUG Checking for package at: 'https://github.com/maplibre/martin/releases/download/0.10.0/martin-x86_64-unknown-linux-gnu-v0.10.0.tar.bz2'
...
DEBUG Checking for package at: 'https://github.com/maplibre/martin/releases/download/0.10.0/martin-x86_64-unknown-linux-gnu-v0.10.0.tar.gz'
..
DEBUG Checking for package at: 'https://github.com/maplibre/martin/releases/download/v0.10.0/martin-x86_64-unknown-linux-gnu-v0.10.0.zip'
...
DEBUG Checking for package at: 'https://github.com/maplibre/martin/releases/download/0.10.0/martin-x86_64-unknown-linux-musl-v0.10.0.zip'
...
```
So update the package names in this PR.
## bin and bin-dir in this PR

|         | bin | bin-dir(windows) | bin-dir(linux)  | bin-dir(macos) |
|---------|--------------------------------------------------------------------------|------------------|-----------------|---------------|
| martin  | martin                                                                   | martin.exe       | martin          | martin        |
| mbtiles | mbtiles                                                                  | mbtiles.exe       | mbtiles         | mbtiles       |


So keep file names still in this PR.

**Comment by nyurik** [comment]
I have merged the CI part of this PR directly into the main branch, and will release it as a pre-release. Once all works and checks out, I will merge this PR as well. Thanks!

**Review by nyurik — APPROVED** [review]
thanks once again!

**Pull request merged**
