### PR TITLE
Upgrade styled componenets to v6

### LINKED ISSUE #996: Upgrade demo site's `styled-components` NPM package to v6
The `/demo/frontend` uses v5 of the `styled-components` npm, and needs to be updated.

See also https://styled-components.com/docs/faqs#what-do-i-need-to-do-to-migrate-to-v6

Updating package.json styled components to 6.1.1 produces this error:

```
cd demo/frontend
just up-build
...
0.471 yarn run v1.22.19
0.493 $ tsc && vite build
5.740 src/Components/Map/Filters/AvgTime.ts(10,15): error TS2339: Property 'isEnabled' does not exist on type 'ExecutionContext & FastOmit<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, never>'.
5.740 src/Components/Map/Filters/Filters.tsx(88,13): error TS2769: No overload matches this call.
5.740   Overload 1 of 2, '(props: PolymorphicComponentProps<"web", FastOmit<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, never>, void, void, {}, {}>): Element', gave the following error.
5.740     Type '{ children: string; isEnabled: boolean; onClick: () => void; }' is not assignable to type 'IntrinsicAttributes & FastOmit<Substitute<FastOmit<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, never>, FastOmit<...>>, keyof ExecutionProps> & FastOmit<...> & { ...; }'.
5.740       Property 'isEnabled' does not exist on type 'IntrinsicAttributes & FastOmit<Substitute<FastOmit<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, never>, FastOmit<...>>, keyof ExecutionProps> & FastOmit<...> & { ...; }'.
5.740   Overload 2 of 2, '(props: FastOmit<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, never>): ReactNode', gave the following error.
5.740     Type '{ children: string; isEnabled: boolean; onClick: () => void; }' is not assignable to type 'IntrinsicAttributes & FastOmit<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, never>'.
5.740       Property 'isEnabled' does not exist on type 'IntrinsicAttributes & FastOmit<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, never>'.
5.740 src/Components/Map/Filters/Layers/Layer.ts(8,15): error TS2339: Property 'isLayerVisible' does not exist on type 'ExecutionContext & FastOmit<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, never>'.
5.740 src/Components/Map/Filters/Layers/Legend.ts(10,12): error TS2339: Property 'fromColor' does not exist on type 'ExecutionContext & FastOmit<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, never>'.
5.740 src/Components/Map/Filters/Layers/Legend.ts(10,23): error TS2339: Property 'toColor' does not exist on type 'ExecutionContext & FastOmit<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, never>'.
5.782 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
5.782 error Command failed with exit code 2.
```

### PR DESCRIPTION
**Pull request by jtmiclat**
Closes #996 

This PR updated styled components to v6.

In v5, styled components had no type checking by default while in v6 it is included by default so I had to add typing to the styled components props.

### CODE REVIEW

**Comment by nyurik** [comment]
i think you are missing the changes to package.json - did you modify that file too?

**Comment by jtmiclat** [comment]
@nyurik Woops forgot to commit package.json . Should be fixed now

**Comment by nyurik** [comment]
Thanks @jtmiclat !   I added a CI step to build the code, so seems to be passing.  Would be great to have some sort of a integration test, but not worth it for a demo site.

**Comment by nyurik** [comment]
@jtmiclat if you have any energy, feel free to bump all other demo dependencies -- it is not as often maintained as one could hope :)

**Pull request merged**
