### PR TITLE
chore(tests): re-blessed all tests

### PR DESCRIPTION
**Pull request by CommanderStorm**
insta currently produces this (quite annoying) warning:

image

=> this PR re-blesses all files to get rid of it

### CODE REVIEW

**Comment by nyurik** [comment]
hopefully it will be fixed soon - and we won't need to re-do it again - so might want to postpone this one.  https://github.com/mitsuhiko/insta/issues/676

**Comment by nyurik** [comment]
lets postpone this for a bit - to see if insta fixes it shortly. If not, we will merge.

**Comment by nyurik** [comment]
looks much cleaner, thx!  One thing to note is that insta hasn't released the new version yet, but I don't think its a big deal

**Review by nyurik — APPROVED** [review]

**Comment by CommanderStorm** [comment]
Considering that dependency updates are done via dependabot, I think merging now and merging the insta bump when it comes avaliable is a good choice

**Pull request merged**
